<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YnWfIX9' shared service.

return $this->privates['.service_locator.YnWfIX9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', 'App\\Repository\\PrestataireRepository', 'getPrestataireRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'partenaire' => 'App\\Repository\\PrestataireRepository',
    'serializer' => '?',
]);
