<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0xDS.HG' shared service.

return $this->privates['.service_locator.0xDS.HG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'JWTEncoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService.php', true],
], [
    'JWTEncoder' => '?',
]);
