<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M70luEQ' shared service.

return $this->privates['.service_locator.M70luEQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'tra' => ['privates', 'App\\Repository\\TransactionsRepository', 'getTransactionsRepositoryService.php', true],
], [
    'serializer' => '?',
    'tra' => 'App\\Repository\\TransactionsRepository',
]);
