<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dGsIgmv' shared service.

return $this->privates['.service_locator.dGsIgmv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::compte' => ['privates', '.service_locator.EEGLKoc', 'get_ServiceLocator_EEGLKocService.php', true],
    'App\\Controller\\CompteController::listecompte' => ['privates', '.service_locator.LGu22KU', 'get_ServiceLocator_LGu22KUService.php', true],
    'App\\Controller\\DepotController::depot' => ['privates', '.service_locator.Yb0Y8ji', 'get_ServiceLocator_Yb0Y8jiService.php', true],
    'App\\Controller\\PrestataireController::ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PrestataireController::index' => ['privates', '.service_locator.YnWfIX9', 'get_ServiceLocator_YnWfIX9Service.php', true],
    'App\\Controller\\TransactionController::envoi' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.qDmvMf.', 'get_ServiceLocator_QDmvMf_Service.php', true],
    'App\\Controller\\UserController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::status' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\CompteController:compte' => ['privates', '.service_locator.EEGLKoc', 'get_ServiceLocator_EEGLKocService.php', true],
    'App\\Controller\\CompteController:listecompte' => ['privates', '.service_locator.LGu22KU', 'get_ServiceLocator_LGu22KUService.php', true],
    'App\\Controller\\DepotController:depot' => ['privates', '.service_locator.Yb0Y8ji', 'get_ServiceLocator_Yb0Y8jiService.php', true],
    'App\\Controller\\PrestataireController:ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PrestataireController:index' => ['privates', '.service_locator.YnWfIX9', 'get_ServiceLocator_YnWfIX9Service.php', true],
    'App\\Controller\\TransactionController:envoi' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.qDmvMf.', 'get_ServiceLocator_QDmvMf_Service.php', true],
    'App\\Controller\\UserController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:status' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
], [
    'App\\Controller\\CompteController::compte' => '?',
    'App\\Controller\\CompteController::listecompte' => '?',
    'App\\Controller\\DepotController::depot' => '?',
    'App\\Controller\\PrestataireController::ajout' => '?',
    'App\\Controller\\PrestataireController::index' => '?',
    'App\\Controller\\TransactionController::envoi' => '?',
    'App\\Controller\\UserController::login' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\UserController::setViewHandler' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\UserController::status' => '?',
    'App\\Controller\\CompteController:compte' => '?',
    'App\\Controller\\CompteController:listecompte' => '?',
    'App\\Controller\\DepotController:depot' => '?',
    'App\\Controller\\PrestataireController:ajout' => '?',
    'App\\Controller\\PrestataireController:index' => '?',
    'App\\Controller\\TransactionController:envoi' => '?',
    'App\\Controller\\UserController:login' => '?',
    'App\\Controller\\UserController:register' => '?',
    'App\\Controller\\UserController:setViewHandler' => '?',
    'App\\Controller\\UserController:show' => '?',
    'App\\Controller\\UserController:status' => '?',
]);
