<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M30T2zO' shared service.

return $this->privates['.service_locator.M30T2zO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compte' => ['privates', '.errored..service_locator.M30T2zO.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.M30T2zO": it references class "App\\Entity\\Compte" but no such service exists.'],
], [
    'compte' => 'App\\Entity\\Compte',
]);
