<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nHdZ33J' shared service.

return $this->privates['.service_locator.nHdZ33J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::compte' => ['privates', '.service_locator.EEGLKoc', 'get_ServiceLocator_EEGLKocService.php', true],
    'App\\Controller\\CompteController::delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController::show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\DepotController::depot' => ['privates', '.service_locator.Yb0Y8ji', 'get_ServiceLocator_Yb0Y8jiService.php', true],
    'App\\Controller\\PrestataireController::ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PrestataireController::index' => ['privates', '.service_locator.YnWfIX9', 'get_ServiceLocator_YnWfIX9Service.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.qDmvMf.', 'get_ServiceLocator_QDmvMf_Service.php', true],
    'App\\Controller\\UserController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\CompteController:compte' => ['privates', '.service_locator.EEGLKoc', 'get_ServiceLocator_EEGLKocService.php', true],
    'App\\Controller\\CompteController:delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController:show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\DepotController:depot' => ['privates', '.service_locator.Yb0Y8ji', 'get_ServiceLocator_Yb0Y8jiService.php', true],
    'App\\Controller\\PrestataireController:ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PrestataireController:index' => ['privates', '.service_locator.YnWfIX9', 'get_ServiceLocator_YnWfIX9Service.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.qDmvMf.', 'get_ServiceLocator_QDmvMf_Service.php', true],
    'App\\Controller\\UserController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
], [
    'App\\Controller\\CompteController::compte' => '?',
    'App\\Controller\\CompteController::delete' => '?',
    'App\\Controller\\CompteController::edit' => '?',
    'App\\Controller\\CompteController::index' => '?',
    'App\\Controller\\CompteController::show' => '?',
    'App\\Controller\\DepotController::depot' => '?',
    'App\\Controller\\PrestataireController::ajout' => '?',
    'App\\Controller\\PrestataireController::index' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\UserController::setViewHandler' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\UserController::userBloquer' => '?',
    'App\\Controller\\CompteController:compte' => '?',
    'App\\Controller\\CompteController:delete' => '?',
    'App\\Controller\\CompteController:edit' => '?',
    'App\\Controller\\CompteController:index' => '?',
    'App\\Controller\\CompteController:show' => '?',
    'App\\Controller\\DepotController:depot' => '?',
    'App\\Controller\\PrestataireController:ajout' => '?',
    'App\\Controller\\PrestataireController:index' => '?',
    'App\\Controller\\UserController:register' => '?',
    'App\\Controller\\UserController:setViewHandler' => '?',
    'App\\Controller\\UserController:show' => '?',
    'App\\Controller\\UserController:userBloquer' => '?',
]);
