<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QRKDbBt' shared service.

return $this->privates['.service_locator.QRKDbBt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'transactionsRepository' => ['privates', 'App\\Repository\\TransactionsRepository', 'getTransactionsRepositoryService.php', true],
], [
    'transactionsRepository' => 'App\\Repository\\TransactionsRepository',
]);
