<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TpB3x5u' shared service.

return $this->privates['.service_locator.TpB3x5u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'transaction' => ['privates', '.errored..service_locator.TpB3x5u.App\\Entity\\Transactions', NULL, 'Cannot autowire service ".service_locator.TpB3x5u": it references class "App\\Entity\\Transactions" but no such service exists.'],
], [
    'transaction' => 'App\\Entity\\Transactions',
]);
