<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.current_date_time_helper' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Naming/DateTimeHelper.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Naming/CurrentDateTimeHelper.php';

return $this->privates['vich_uploader.current_date_time_helper'] = new \Vich\UploaderBundle\Naming\CurrentDateTimeHelper();
