<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0Zq9tt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0Zq9tt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK0Zq9tt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK0Zq9tt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK0Zq9tt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K0Zq9tt',
    'container.build_id' => '47416c1a',
    'container.build_time' => 1567791309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0Zq9tt');
