<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDQRyx0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDQRyx0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDQRyx0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDQRyx0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVDQRyx0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VDQRyx0',
    'container.build_id' => '181dc226',
    'container.build_time' => 1567264855,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDQRyx0');
